# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-05 09:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_social'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='social',
            options={'verbose_name_plural': 'Social media links'},
        ),
        migrations.AddField(
            model_name='thing',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 9, 5, 9, 38, 23, 223836, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thing',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 9, 5, 9, 38, 41, 180774, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
